# coding: utf-8

"""
    FlashArray REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.X
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re

import six
import typing

from ....properties import Property
if typing.TYPE_CHECKING:
    from pypureclient.flasharray.FA_2_X import models

class DirectoryUserQuota(object):
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'context': 'FixedReferenceWithType',
        'directory': 'FixedReferenceWithType',
        'path': 'str',
        'percentage_used': 'float',
        'quota_usage': 'int',
        'rule': 'DirectoryUserQuotaRule',
        'user': 'UserGroup',
        'user_email': 'str'
    }

    attribute_map = {
        'context': 'context',
        'directory': 'directory',
        'path': 'path',
        'percentage_used': 'percentage_used',
        'quota_usage': 'quota_usage',
        'rule': 'rule',
        'user': 'user',
        'user_email': 'user_email'
    }

    required_args = {
    }

    def __init__(
        self,
        context=None,  # type: models.FixedReferenceWithType
        directory=None,  # type: models.FixedReferenceWithType
        path=None,  # type: str
        percentage_used=None,  # type: float
        quota_usage=None,  # type: int
        rule=None,  # type: models.DirectoryUserQuotaRule
        user=None,  # type: models.UserGroup
        user_email=None,  # type: str
    ):
        """
        Keyword args:
            context (FixedReferenceWithType): The context in which the operation was performed. Valid values include a reference to any array which is a member of the same fleet.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided `context`. 
            directory (FixedReferenceWithType): The directory with the user-group-quota policy attached. 
            path (str): Absolute path of the managed directory in the file system. 
            percentage_used (float): The ratio of the quota usage to the quota limit, with 1.0 meaning that the usage has reached the quota limit. 
            quota_usage (int): The total usage owned by the user that is accountable to the user-group-quota policy rules. The applicable rules may be enforced or unenforced. The usage is measured in bytes. 
            rule (DirectoryUserQuotaRule): The user-group-quota rule that applies to the user. 
            user (UserGroup): The user for which the user-group-quota policy rules apply. 
            user_email (str): The email address of the user. 
        """
        if context is not None:
            self.context = context
        if directory is not None:
            self.directory = directory
        if path is not None:
            self.path = path
        if percentage_used is not None:
            self.percentage_used = percentage_used
        if quota_usage is not None:
            self.quota_usage = quota_usage
        if rule is not None:
            self.rule = rule
        if user is not None:
            self.user = user
        if user_email is not None:
            self.user_email = user_email

    def __setattr__(self, key, value):
        if key not in self.attribute_map:
            raise KeyError("Invalid key `{}` for `DirectoryUserQuota`".format(key))
        self.__dict__[key] = value

    def __getattribute__(self, item):
        value = object.__getattribute__(self, item)
        if isinstance(value, Property):
            raise AttributeError
        else:
            return value

    def __getitem__(self, key):
        if key not in self.attribute_map:
            raise KeyError("Invalid key `{}` for `DirectoryUserQuota`".format(key))
        return object.__getattribute__(self, key)

    def __setitem__(self, key, value):
        if key not in self.attribute_map:
            raise KeyError("Invalid key `{}` for `DirectoryUserQuota`".format(key))
        object.__setattr__(self, key, value)

    def __delitem__(self, key):
        if key not in self.attribute_map:
            raise KeyError("Invalid key `{}` for `DirectoryUserQuota`".format(key))
        object.__delattr__(self, key)

    def keys(self):
        return self.attribute_map.keys()

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            if hasattr(self, attr):
                value = getattr(self, attr)
                if isinstance(value, list):
                    result[attr] = list(map(
                        lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                        value
                    ))
                elif hasattr(value, "to_dict"):
                    result[attr] = value.to_dict()
                elif isinstance(value, dict):
                    result[attr] = dict(map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict") else item,
                        value.items()
                    ))
                else:
                    result[attr] = value
        if issubclass(DirectoryUserQuota, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DirectoryUserQuota):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
