# coding: utf-8

"""
    FlashArray REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.X
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re

import six
import typing

from ....properties import Property
if typing.TYPE_CHECKING:
    from pypureclient.flasharray.FA_2_X import models

class NetworkInterfacePerformanceEth(object):
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'carrier_changes_per_sec': 'int',
        'flow_control_received_congestion_packets_per_sec': 'int',
        'flow_control_received_discarded_packets_per_sec': 'int',
        'flow_control_received_lossless_bytes_per_sec': 'int',
        'flow_control_received_pause_frames_per_sec': 'int',
        'flow_control_transmitted_congestion_packets_per_sec': 'int',
        'flow_control_transmitted_discarded_packets_per_sec': 'int',
        'flow_control_transmitted_lossless_bytes_per_sec': 'int',
        'flow_control_transmitted_pause_frames_per_sec': 'int',
        'other_errors_per_sec': 'int',
        'rdma_received_req_cqe_errors_per_sec': 'int',
        'rdma_received_sequence_errors_per_sec': 'int',
        'rdma_transmitted_local_ack_timeout_errors_per_sec': 'int',
        'received_bytes_per_sec': 'int',
        'received_crc_errors': 'int',
        'received_crc_errors_per_sec': 'int',
        'received_frame_errors': 'int',
        'received_frame_errors_per_sec': 'int',
        'received_packets_per_sec': 'int',
        'sample_period': 'int',
        'total_errors': 'int',
        'total_errors_per_sec': 'int',
        'transmitted_bytes_per_sec': 'int',
        'transmitted_carrier_errors': 'int',
        'transmitted_carrier_errors_per_sec': 'int',
        'transmitted_dropped_errors': 'int',
        'transmitted_dropped_errors_per_sec': 'int',
        'transmitted_packets_per_sec': 'int'
    }

    attribute_map = {
        'carrier_changes_per_sec': 'carrier_changes_per_sec',
        'flow_control_received_congestion_packets_per_sec': 'flow_control_received_congestion_packets_per_sec',
        'flow_control_received_discarded_packets_per_sec': 'flow_control_received_discarded_packets_per_sec',
        'flow_control_received_lossless_bytes_per_sec': 'flow_control_received_lossless_bytes_per_sec',
        'flow_control_received_pause_frames_per_sec': 'flow_control_received_pause_frames_per_sec',
        'flow_control_transmitted_congestion_packets_per_sec': 'flow_control_transmitted_congestion_packets_per_sec',
        'flow_control_transmitted_discarded_packets_per_sec': 'flow_control_transmitted_discarded_packets_per_sec',
        'flow_control_transmitted_lossless_bytes_per_sec': 'flow_control_transmitted_lossless_bytes_per_sec',
        'flow_control_transmitted_pause_frames_per_sec': 'flow_control_transmitted_pause_frames_per_sec',
        'other_errors_per_sec': 'other_errors_per_sec',
        'rdma_received_req_cqe_errors_per_sec': 'rdma_received_req_cqe_errors_per_sec',
        'rdma_received_sequence_errors_per_sec': 'rdma_received_sequence_errors_per_sec',
        'rdma_transmitted_local_ack_timeout_errors_per_sec': 'rdma_transmitted_local_ack_timeout_errors_per_sec',
        'received_bytes_per_sec': 'received_bytes_per_sec',
        'received_crc_errors': 'received_crc_errors',
        'received_crc_errors_per_sec': 'received_crc_errors_per_sec',
        'received_frame_errors': 'received_frame_errors',
        'received_frame_errors_per_sec': 'received_frame_errors_per_sec',
        'received_packets_per_sec': 'received_packets_per_sec',
        'sample_period': 'sample_period',
        'total_errors': 'total_errors',
        'total_errors_per_sec': 'total_errors_per_sec',
        'transmitted_bytes_per_sec': 'transmitted_bytes_per_sec',
        'transmitted_carrier_errors': 'transmitted_carrier_errors',
        'transmitted_carrier_errors_per_sec': 'transmitted_carrier_errors_per_sec',
        'transmitted_dropped_errors': 'transmitted_dropped_errors',
        'transmitted_dropped_errors_per_sec': 'transmitted_dropped_errors_per_sec',
        'transmitted_packets_per_sec': 'transmitted_packets_per_sec'
    }

    required_args = {
    }

    def __init__(
        self,
        carrier_changes_per_sec=None,  # type: int
        flow_control_received_congestion_packets_per_sec=None,  # type: int
        flow_control_received_discarded_packets_per_sec=None,  # type: int
        flow_control_received_lossless_bytes_per_sec=None,  # type: int
        flow_control_received_pause_frames_per_sec=None,  # type: int
        flow_control_transmitted_congestion_packets_per_sec=None,  # type: int
        flow_control_transmitted_discarded_packets_per_sec=None,  # type: int
        flow_control_transmitted_lossless_bytes_per_sec=None,  # type: int
        flow_control_transmitted_pause_frames_per_sec=None,  # type: int
        other_errors_per_sec=None,  # type: int
        rdma_received_req_cqe_errors_per_sec=None,  # type: int
        rdma_received_sequence_errors_per_sec=None,  # type: int
        rdma_transmitted_local_ack_timeout_errors_per_sec=None,  # type: int
        received_bytes_per_sec=None,  # type: int
        received_crc_errors=None,  # type: int
        received_crc_errors_per_sec=None,  # type: int
        received_frame_errors=None,  # type: int
        received_frame_errors_per_sec=None,  # type: int
        received_packets_per_sec=None,  # type: int
        sample_period=None,  # type: int
        total_errors=None,  # type: int
        total_errors_per_sec=None,  # type: int
        transmitted_bytes_per_sec=None,  # type: int
        transmitted_carrier_errors=None,  # type: int
        transmitted_carrier_errors_per_sec=None,  # type: int
        transmitted_dropped_errors=None,  # type: int
        transmitted_dropped_errors_per_sec=None,  # type: int
        transmitted_packets_per_sec=None,  # type: int
    ):
        """
        Keyword args:
            carrier_changes_per_sec (int): Carrier changes per second. 
            flow_control_received_congestion_packets_per_sec (int): Number of congestion control packets received per second. 
            flow_control_received_discarded_packets_per_sec (int): Number of received packets that were physically discarded by the NIC per second due to errors or other reasons. 
            flow_control_received_lossless_bytes_per_sec (int): Bytes received per second with lossless flow control settings. 
            flow_control_received_pause_frames_per_sec (int): Received pause frames per second. 
            flow_control_transmitted_congestion_packets_per_sec (int): Number of congestion control packets transmitted per second. 
            flow_control_transmitted_discarded_packets_per_sec (int): Number of transmitted packets that were physically discarded by the NIC per second due to errors or other reasons. 
            flow_control_transmitted_lossless_bytes_per_sec (int): Bytes transmitted per second with lossless flow control settings. 
            flow_control_transmitted_pause_frames_per_sec (int): Transmitted pause frames per second. 
            other_errors_per_sec (int): This field has been deprecated. Since Purity version 6.6.8, this will always return `null`. The sum of unspecified reception and transmission errors per second. 
            rdma_received_req_cqe_errors_per_sec (int): The number of times port detected RDMA CQEs with error per second. 
            rdma_received_sequence_errors_per_sec (int): The number of received RDMA packet sequence errors per second. 
            rdma_transmitted_local_ack_timeout_errors_per_sec (int): The number of times RDMA ack timer expired for QPs per second. 
            received_bytes_per_sec (int): Bytes received per second. 
            received_crc_errors (int): CRC errors received during the “sample_period”. 
            received_crc_errors_per_sec (int): This field has been deprecated. Please use the \"received_crc_errors\" instead. 
            received_frame_errors (int): Received packet frame errors during the “sample_period”. 
            received_frame_errors_per_sec (int): This field has been deprecated. Please use the \"received_frame_errors\" instead. 
            received_packets_per_sec (int): Packets received per second. 
            sample_period (int): Sample duration for stats in milliseconds. 
            total_errors (int): The sum of all reception and transmission errors received during the “sample_period”. 
            total_errors_per_sec (int): This field has been deprecated. Please use the \"total_errors\" instead. 
            transmitted_bytes_per_sec (int): Bytes transmitted per second. 
            transmitted_carrier_errors (int): Transmission carrier errors during the “sample_period”. 
            transmitted_carrier_errors_per_sec (int): This field has been deprecated. Please use the \"transmitted_carrier_errors\" instead. 
            transmitted_dropped_errors (int): Transmitted packets dropped during the “sample_period”. 
            transmitted_dropped_errors_per_sec (int): This field has been deprecated. Please use the \"transmitted_dropped_errors\" instead. 
            transmitted_packets_per_sec (int): Packets transmitted per second. 
        """
        if carrier_changes_per_sec is not None:
            self.carrier_changes_per_sec = carrier_changes_per_sec
        if flow_control_received_congestion_packets_per_sec is not None:
            self.flow_control_received_congestion_packets_per_sec = flow_control_received_congestion_packets_per_sec
        if flow_control_received_discarded_packets_per_sec is not None:
            self.flow_control_received_discarded_packets_per_sec = flow_control_received_discarded_packets_per_sec
        if flow_control_received_lossless_bytes_per_sec is not None:
            self.flow_control_received_lossless_bytes_per_sec = flow_control_received_lossless_bytes_per_sec
        if flow_control_received_pause_frames_per_sec is not None:
            self.flow_control_received_pause_frames_per_sec = flow_control_received_pause_frames_per_sec
        if flow_control_transmitted_congestion_packets_per_sec is not None:
            self.flow_control_transmitted_congestion_packets_per_sec = flow_control_transmitted_congestion_packets_per_sec
        if flow_control_transmitted_discarded_packets_per_sec is not None:
            self.flow_control_transmitted_discarded_packets_per_sec = flow_control_transmitted_discarded_packets_per_sec
        if flow_control_transmitted_lossless_bytes_per_sec is not None:
            self.flow_control_transmitted_lossless_bytes_per_sec = flow_control_transmitted_lossless_bytes_per_sec
        if flow_control_transmitted_pause_frames_per_sec is not None:
            self.flow_control_transmitted_pause_frames_per_sec = flow_control_transmitted_pause_frames_per_sec
        if other_errors_per_sec is not None:
            self.other_errors_per_sec = other_errors_per_sec
        if rdma_received_req_cqe_errors_per_sec is not None:
            self.rdma_received_req_cqe_errors_per_sec = rdma_received_req_cqe_errors_per_sec
        if rdma_received_sequence_errors_per_sec is not None:
            self.rdma_received_sequence_errors_per_sec = rdma_received_sequence_errors_per_sec
        if rdma_transmitted_local_ack_timeout_errors_per_sec is not None:
            self.rdma_transmitted_local_ack_timeout_errors_per_sec = rdma_transmitted_local_ack_timeout_errors_per_sec
        if received_bytes_per_sec is not None:
            self.received_bytes_per_sec = received_bytes_per_sec
        if received_crc_errors is not None:
            self.received_crc_errors = received_crc_errors
        if received_crc_errors_per_sec is not None:
            self.received_crc_errors_per_sec = received_crc_errors_per_sec
        if received_frame_errors is not None:
            self.received_frame_errors = received_frame_errors
        if received_frame_errors_per_sec is not None:
            self.received_frame_errors_per_sec = received_frame_errors_per_sec
        if received_packets_per_sec is not None:
            self.received_packets_per_sec = received_packets_per_sec
        if sample_period is not None:
            self.sample_period = sample_period
        if total_errors is not None:
            self.total_errors = total_errors
        if total_errors_per_sec is not None:
            self.total_errors_per_sec = total_errors_per_sec
        if transmitted_bytes_per_sec is not None:
            self.transmitted_bytes_per_sec = transmitted_bytes_per_sec
        if transmitted_carrier_errors is not None:
            self.transmitted_carrier_errors = transmitted_carrier_errors
        if transmitted_carrier_errors_per_sec is not None:
            self.transmitted_carrier_errors_per_sec = transmitted_carrier_errors_per_sec
        if transmitted_dropped_errors is not None:
            self.transmitted_dropped_errors = transmitted_dropped_errors
        if transmitted_dropped_errors_per_sec is not None:
            self.transmitted_dropped_errors_per_sec = transmitted_dropped_errors_per_sec
        if transmitted_packets_per_sec is not None:
            self.transmitted_packets_per_sec = transmitted_packets_per_sec

    def __setattr__(self, key, value):
        if key not in self.attribute_map:
            raise KeyError("Invalid key `{}` for `NetworkInterfacePerformanceEth`".format(key))
        if key == "carrier_changes_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `carrier_changes_per_sec`, must be a value greater than or equal to `0`")
        if key == "flow_control_received_congestion_packets_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `flow_control_received_congestion_packets_per_sec`, must be a value greater than or equal to `0`")
        if key == "flow_control_received_discarded_packets_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `flow_control_received_discarded_packets_per_sec`, must be a value greater than or equal to `0`")
        if key == "flow_control_received_lossless_bytes_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `flow_control_received_lossless_bytes_per_sec`, must be a value greater than or equal to `0`")
        if key == "flow_control_received_pause_frames_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `flow_control_received_pause_frames_per_sec`, must be a value greater than or equal to `0`")
        if key == "flow_control_transmitted_congestion_packets_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `flow_control_transmitted_congestion_packets_per_sec`, must be a value greater than or equal to `0`")
        if key == "flow_control_transmitted_discarded_packets_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `flow_control_transmitted_discarded_packets_per_sec`, must be a value greater than or equal to `0`")
        if key == "flow_control_transmitted_lossless_bytes_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `flow_control_transmitted_lossless_bytes_per_sec`, must be a value greater than or equal to `0`")
        if key == "flow_control_transmitted_pause_frames_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `flow_control_transmitted_pause_frames_per_sec`, must be a value greater than or equal to `0`")
        if key == "other_errors_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `other_errors_per_sec`, must be a value greater than or equal to `0`")
        if key == "rdma_received_req_cqe_errors_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `rdma_received_req_cqe_errors_per_sec`, must be a value greater than or equal to `0`")
        if key == "rdma_received_sequence_errors_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `rdma_received_sequence_errors_per_sec`, must be a value greater than or equal to `0`")
        if key == "rdma_transmitted_local_ack_timeout_errors_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `rdma_transmitted_local_ack_timeout_errors_per_sec`, must be a value greater than or equal to `0`")
        if key == "received_bytes_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `received_bytes_per_sec`, must be a value greater than or equal to `0`")
        if key == "received_crc_errors" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `received_crc_errors`, must be a value greater than or equal to `0`")
        if key == "received_crc_errors_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `received_crc_errors_per_sec`, must be a value greater than or equal to `0`")
        if key == "received_frame_errors" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `received_frame_errors`, must be a value greater than or equal to `0`")
        if key == "received_frame_errors_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `received_frame_errors_per_sec`, must be a value greater than or equal to `0`")
        if key == "received_packets_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `received_packets_per_sec`, must be a value greater than or equal to `0`")
        if key == "sample_period" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `sample_period`, must be a value greater than or equal to `0`")
        if key == "total_errors" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `total_errors`, must be a value greater than or equal to `0`")
        if key == "total_errors_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `total_errors_per_sec`, must be a value greater than or equal to `0`")
        if key == "transmitted_bytes_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `transmitted_bytes_per_sec`, must be a value greater than or equal to `0`")
        if key == "transmitted_carrier_errors" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `transmitted_carrier_errors`, must be a value greater than or equal to `0`")
        if key == "transmitted_carrier_errors_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `transmitted_carrier_errors_per_sec`, must be a value greater than or equal to `0`")
        if key == "transmitted_dropped_errors" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `transmitted_dropped_errors`, must be a value greater than or equal to `0`")
        if key == "transmitted_dropped_errors_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `transmitted_dropped_errors_per_sec`, must be a value greater than or equal to `0`")
        if key == "transmitted_packets_per_sec" and value is not None:
            if value < 0:
                raise ValueError("Invalid value for `transmitted_packets_per_sec`, must be a value greater than or equal to `0`")
        self.__dict__[key] = value

    def __getattribute__(self, item):
        value = object.__getattribute__(self, item)
        if isinstance(value, Property):
            raise AttributeError
        else:
            return value

    def __getitem__(self, key):
        if key not in self.attribute_map:
            raise KeyError("Invalid key `{}` for `NetworkInterfacePerformanceEth`".format(key))
        return object.__getattribute__(self, key)

    def __setitem__(self, key, value):
        if key not in self.attribute_map:
            raise KeyError("Invalid key `{}` for `NetworkInterfacePerformanceEth`".format(key))
        object.__setattr__(self, key, value)

    def __delitem__(self, key):
        if key not in self.attribute_map:
            raise KeyError("Invalid key `{}` for `NetworkInterfacePerformanceEth`".format(key))
        object.__delattr__(self, key)

    def keys(self):
        return self.attribute_map.keys()

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            if hasattr(self, attr):
                value = getattr(self, attr)
                if isinstance(value, list):
                    result[attr] = list(map(
                        lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                        value
                    ))
                elif hasattr(value, "to_dict"):
                    result[attr] = value.to_dict()
                elif isinstance(value, dict):
                    result[attr] = dict(map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict") else item,
                        value.items()
                    ))
                else:
                    result[attr] = value
        if issubclass(NetworkInterfacePerformanceEth, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetworkInterfacePerformanceEth):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
